Stat svc
mikadim/java-explore-with-me pull request #3
Opened 2023-04-11 22:15 UTC by mikadim

2023-04-12 17:18 UTC, Frilock requested changes
Добрый день, пара незначительных комментариев

2023-04-12 17:18 UTC, Frilock commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Давайте версию в properties вынесем

2023-04-12 17:18 UTC, Frilock commented on stats/stat-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +
Можно на тернарное выражение заменить

2023-04-12 17:18 UTC, Frilock commented on stats/stat-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +        Stat newStat = statRepository.save(statMapper.toStat(stat));
Зачем Stat newStat = ?

2023-04-12 17:18 UTC, Frilock commented on stats/stat-server/src/main/resources/schema.sql
> +    app VARCHAR NOT NULL,
Для полей по хорошему размерность нужно продумать, и указать в скрипте и в аннотации Column на ентити

2023-04-13 20:04 UTC, mikadim commented on main-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Доброго времени! ок
вообще пробовал в dependencyManagement закинуть эту зависимость, да и не только туда, проект в итоге не собирался, пришлось с таким вариантом оставить

2023-04-13 20:14 UTC, mikadim commented on stats/stat-server/src/main/java/ru/practicum/service/StatServiceImpl.java
> +        Stat newStat = statRepository.save(statMapper.toStat(stat));
там хитрый тест постман из нескольких запросов в одном тесте, не мог понять что у меня не так, это остатки экспериментов так сказать
убрал...

2023-04-14 15:44 UTC, Frilock approved these changes
Принято

2023-04-14 15:44 UTC, Frilock commented on stats/stat-server/pom.xml
> +            <version>${stat-dto.version}</version>
У вас 1 проект, по идее версия одна будет. Можно просто project.version сделать

2023-04-15 12:15 UTC, merged

2023-04-17 18:16 UTC, mikadim commented on stats/stat-server/pom.xml
> +            <version>${stat-dto.version}</version>
фикс